//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountSeller.Domain.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InformationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InformationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountSeller.Domain.Messages.InformationMessages", typeof(InformationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated order request information..
        /// </summary>
        public static string IM0001 {
            get {
                return ResourceManager.GetString("IM0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has registered..
        /// </summary>
        public static string IM0002 {
            get {
                return ResourceManager.GetString("IM0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has been updated..
        /// </summary>
        public static string IM0003 {
            get {
                return ResourceManager.GetString("IM0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output completed..
        /// </summary>
        public static string IM0004 {
            get {
                return ResourceManager.GetString("IM0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan loading is complete..
        /// </summary>
        public static string IM0005 {
            get {
                return ResourceManager.GetString("IM0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download completed..
        /// </summary>
        public static string IM0007 {
            get {
                return ResourceManager.GetString("IM0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload completed..
        /// </summary>
        public static string IM0008 {
            get {
                return ResourceManager.GetString("IM0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval completed..
        /// </summary>
        public static string IM0009 {
            get {
                return ResourceManager.GetString("IM0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After confirmation, the billing data will be changed..
        /// </summary>
        public static string IM0010 {
            get {
                return ResourceManager.GetString("IM0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have processed the confirmation..
        /// </summary>
        public static string IM0011 {
            get {
                return ResourceManager.GetString("IM0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is modified from {1}..
        /// </summary>
        public static string IM0012 {
            get {
                return ResourceManager.GetString("IM0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully changed your password. Please login again..
        /// </summary>
        public static string IM0013 {
            get {
                return ResourceManager.GetString("IM0013", resourceCulture);
            }
        }
    }
}
