//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountSeller.Domain.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountSeller.Domain.Messages.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid effective month [{0}] specified..
        /// </summary>
        public static string VM0001 {
            get {
                return ResourceManager.GetString("VM0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not set..
        /// </summary>
        public static string VM0002 {
            get {
                return ResourceManager.GetString("VM0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not entered..
        /// </summary>
        public static string VM0003 {
            get {
                return ResourceManager.GetString("VM0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exceeds the maximum number of characters..
        /// </summary>
        public static string VM0004 {
            get {
                return ResourceManager.GetString("VM0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} exceeds the maximum number of rows..
        /// </summary>
        public static string VM0008 {
            get {
                return ResourceManager.GetString("VM0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of characters in line {0} of {1} exceeds the maximum..
        /// </summary>
        public static string VM0009 {
            get {
                return ResourceManager.GetString("VM0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect user and password.
        /// </summary>
        public static string VM0065 {
            get {
                return ResourceManager.GetString("VM0065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This ID is already registered..
        /// </summary>
        public static string VM0118 {
            get {
                return ResourceManager.GetString("VM0118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user ID will be duplicated with the ID of the user who has already been deleted.
        /// </summary>
        public static string VM0121 {
            get {
                return ResourceManager.GetString("VM0121", resourceCulture);
            }
        }
    }
}
