//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountSeller.Domain.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WarningMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarningMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountSeller.Domain.Messages.WarningMessages", typeof(WarningMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create. Is it OK?.
        /// </summary>
        public static string WM0001 {
            get {
                return ResourceManager.GetString("WM0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete. Is it OK?.
        /// </summary>
        public static string WM0002 {
            get {
                return ResourceManager.GetString("WM0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen changes are not registered. Discard changes?.
        /// </summary>
        public static string WM0003 {
            get {
                return ResourceManager.GetString("WM0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It has been updated by another terminal. Are you sure you want to continue processing?.
        /// </summary>
        public static string WM0004 {
            get {
                return ResourceManager.GetString("WM0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update. Is it OK?.
        /// </summary>
        public static string WM0005 {
            get {
                return ResourceManager.GetString("WM0005", resourceCulture);
            }
        }
    }
}
